package jb.model;

public enum ThreadTransition {
    START, SLEEP_TIME, WAIT_TIMEOUT, JOIN_TIMEOUT, PARK_NANOS, WAIT, JOIN, PARK, WAITING_FOR_LOCK, TIME_ELAPSED, NOTIFY, NOTIFY_ALL, LOCK_ACQUIRED, EXIT
}
